name: Docker Build & Publish

# Trigger on all push events, new semantic version tags, and all PRs
on:
  push:
    branches:
      - "main"
      - "v*"
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: "The checkout reference (ie tag, branch, sha)"
        required: true
        type: string

jobs:
  docker-standalone-build:
    permissions:
      contents: write
      packages: write
    uses: celestiaorg/.github/.github/workflows/reusable_dockerfile_pipeline.yml@v0.6.4
    with:
      dockerfile: docker/horcrux/Dockerfile
      checkout_ref: ${{ github.event.inputs.ref }}
      packageName: celestia-horcrux
    secrets: inherit